# .streamlit/config.toml
[theme]
primaryColor = "#6C63FF"          # A vibrant purple for primary actions/highlights
backgroundColor = "#F0F2F6"        # Light grey background
secondaryBackgroundColor = "#FFFFFF" # White for secondary elements like sidebars and containers
textColor = "#262626"              # Dark grey for general text for good readability
font = "sans serif"